In [1]:
# importing numpy
import numpy as np

In [2]:
# Creating Arrays
# From a list
array_from_list = np.array([1, 2, 3, 4, 5])

# Using arange (creates an array with a range of values)
array_with_range = np.arange(0, 10, 2)  # Start at 0, end at 10, step by 2

# Using linspace (creates an array with a specified number of elements)
array_with_linspace = np.linspace(0, 1, 5)  # Start at 0, end at 1, 5 elements

# Using zeros, ones, full, and empty
array_of_zeros = np.zeros((2, 3))  # 2x3 array of zeros
array_of_ones = np.ones((2, 3))    # 2x3 array of ones
array_of_full = np.full((2, 3), 7) # 2x3 array of sevens
array_of_empty = np.empty((2, 3))  # 2x3 array, uninitialized

# Identity matrix
identity_matrix = np.eye(3)        # 3x3 identity matrix

# Random arrays
random_array = np.random.random((2, 3))  # 2x3 array with random floats in [0, 1)


In [3]:
# Array Attributes
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)  # (2, 3) - dimensions of the array
print(array.size)   # 6 - total number of elements
print(array.dtype)  # int64 - data type of elements
print(array.ndim)   # 2 - number of dimensions


(2, 3)
6
int32
2


In [4]:
# Reshaping Arrays
reshaped_array = array.reshape((3, 2))  # Reshape to 3 rows, 2 columns

In [5]:
# Indexing and Slicing

array = np.array([1, 2, 3, 4, 5])

print(array[0])     # First element
print(array[-1])    # Last element
print(array[1:4])   # Slice from index 1 to 3
print(array[::2])   # Every second element

# multidimensional arrays
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(array_2d[0, 1])  # Element at row 0, column 1
print(array_2d[:, 1])  # All rows, column 1
print(array_2d[1, :])  # Row 1, all columns


1
5
[2 3 4]
[1 3 5]
2
[2 5]
[4 5 6]


In [6]:
# Operations on Arrays
array = np.array([1, 2, 3, 4, 5])

# Element-wise operations
print(array + 1)     # [2, 3, 4, 5, 6]
print(array * 2)     # [2, 4, 6, 8, 10]

# Element-wise arithmetic with another array
array2 = np.array([5, 4, 3, 2, 1])
print(array + array2)  # [6, 6, 6, 6, 6]
print(array * array2)  # [5, 8, 9, 8, 5]

# Matrix multiplication
array2d = np.array([[1, 2], [3, 4]])
matrix_multiplication = np.dot(array2d, array2d)


[2 3 4 5 6]
[ 2  4  6  8 10]
[6 6 6 6 6]
[5 8 9 8 5]


In [7]:
# Aggregate Functions
array = np.array([1, 2, 3, 4, 5])

print(np.sum(array))     # Sum of elements
print(np.mean(array))    # Mean of elements
print(np.max(array))     # Maximum element
print(np.min(array))     # Minimum element
print(np.std(array))     # Standard deviation


15
3.0
5
1
1.4142135623730951


In [8]:
# Broadcasting
array1 = np.array([1, 2, 3])
array2 = np.array([[0], [1], [2]])

# Broadcast array1 to the shape of array2 and add
result = array1 + array2
# result: array([[1, 2, 3],
#                [2, 3, 4],
#                [3, 4, 5]])


In [9]:
# Random Number Generation
# Generate random floats in [0, 1)
random_floats = np.random.random((2, 3))

# Generate random integers
random_integers = np.random.randint(1, 10, (2, 3))

# Generate random numbers from a normal distribution
random_normals = np.random.normal(0, 1, (2, 3))

# Set a random seed for reproducibility
np.random.seed(42)
random_floats_seeded = np.random.random((2, 3))


In [10]:
# Saving and Loading
# Save to a binary file in .npy format
np.save('array.npy', array)

# Load from the binary file
loaded_array = np.load('array.npy')

# Save to a text file in .csv format
np.savetxt('array.csv', array, delimiter=',')

# Load from a text file
loaded_array = np.loadtxt('array.csv', delimiter=',')


In [11]:
# Boolean Indexing
array = np.array([1, 2, 3, 4, 5])

# Boolean indexing
bool_idx = array > 3
print(array[bool_idx])  # [4, 5]

# Directly using conditions
print(array[array % 2 == 0])  # [2, 4]


[4 5]
[2 4]


In [12]:
# Fancy Indexing
array = np.array([10, 20, 30, 40, 50])

# Fancy indexing
indices = [1, 3, 4]
print(array[indices])  # [20, 40, 50]

# Fancy indexing with multidimensional arrays
array2d = np.array([[1, 2], [3, 4], [5, 6]])
rows = np.array([0, 1, 2])
cols = np.array([1, 1, 0])
print(array2d[rows, cols])  # [2, 4, 5]


[20 40 50]
[2 4 5]


In [13]:
# Linear Algebra
from numpy.linalg import inv, eig, solve, det

# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

# Inverse of the matrix
matrix_inv = inv(matrix)
print(matrix_inv)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(matrix)
print(eigenvalues)
print(eigenvectors)

# Solving a system of linear equations
# 2x + y = 8
# 3x + 2y = 18
A = np.array([[2, 1], [3, 2]])
B = np.array([8, 18])
solutions = solve(A, B)
print(solutions)  # [4. 0.]

# Determinant of the matrix
matrix_det = det(matrix)
print(matrix_det)  # -2.0


[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[-2. 12.]
-2.0000000000000004


In [14]:
# Statistical Functions
array = np.array([1, 2, 3, 4, 5, 6])

# Basic statistical functions
print(np.mean(array))  # Mean: 3.5
print(np.median(array))  # Median: 3.5
print(np.std(array))  # Standard deviation: 1.707825127659933
print(np.var(array))  # Variance: 2.9166666666666665

# Percentiles
print(np.percentile(array, 50))  # 50th percentile (median): 3.5
print(np.percentile(array, 75))  # 75th percentile: 5.25


3.5
3.5
1.707825127659933
2.9166666666666665
3.5
4.75


In [15]:
# Stacking Arrays
array1 = np.array([1, 2])
array2 = np.array([3, 4])

# Vertical stack
vstacked = np.vstack((array1, array2))
print(vstacked)
# Output:
# [[1 2]
#  [3 4]]

# Horizontal stack
hstacked = np.hstack((array1, array2))
print(hstacked)
# Output: [1 2 3 4]

# Depth stack (stack along a third axis)
dstacked = np.dstack((array1, array2))
print(dstacked)
# Output: [[[1 3]
#           [2 4]]]


[[1 2]
 [3 4]]
[1 2 3 4]
[[[1 3]
  [2 4]]]


In [16]:
# Splitting Arrays
array = np.array([[1, 2, 3, 4, 5, 6]])

# Split into 3 arrays
split_array = np.hsplit(array, 3)
print(split_array)
# Output: [array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

# Vertical split (2D array)
array2d = np.array([[1, 2, 3], [4, 5, 6]])
vsplit_array = np.vsplit(array2d, 2)
print(vsplit_array)
# Output: [array([[1, 2, 3]]), array([[4, 5, 6]])]


[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [17]:
# Sorting
array = np.array([3, 1, 2, 5, 4])

# Sort array
sorted_array = np.sort(array)
print(sorted_array)  # [1, 2, 3, 4, 5]

# Sort along an axis (2D array)
array2d = np.array([[3, 1, 2], [6, 5, 4]])
sorted_array2d = np.sort(array2d, axis=1)
print(sorted_array2d)
# Output:
# [[1 2 3]
#  [4 5 6]]


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [18]:
# Searching
array = np.array([1, 2, 3, 4, 5])

# Search for specific value
index = np.where(array == 3)
print(index)  # (array([2]),)

# Search for values greater than 3
indices = np.where(array > 3)
print(indices)  # (array([3, 4]),)

# Find indices of sorted array
sorted_indices = np.argsort(array)
print(sorted_indices)  # [0 1 2 3 4]


(array([2], dtype=int64),)
(array([3, 4], dtype=int64),)
[0 1 2 3 4]


In [19]:
# Mathematical Functions
array = np.array([0, np.pi/2, np.pi])

# Trigonometric functions
sin_array = np.sin(array)
print(sin_array)  # [0. 1. 0.]

# Exponential and logarithmic functions
exp_array = np.exp(array)
print(exp_array)  # [ 1.          1.64872127 20.08553692]

log_array = np.log(np.array([1, np.e, np.e**2]))
print(log_array)  # [0. 1. 2.]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]
[0. 1. 2.]


In [20]:
from numpy.linalg import svd

# Matrix Operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.matmul(matrix1, matrix2)
print(result)
# Output:
# [[19 22]
#  [43 50]]

# Singular Value Decomposition (SVD)
matrix = np.array([[1, 2], [3, 4]])

# Perform SVD
U, S, Vt = svd(matrix)
print("U:", U)
print("S:", S)
print("Vt:", Vt)


[[19 22]
 [43 50]]
U: [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S: [5.4649857  0.36596619]
Vt: [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [21]:
# Polynomials
from numpy.polynomial import Polynomial

# Create a polynomial: p(x) = 1 + 2x + 3x^2
p = Polynomial([1, 2, 3])

# Evaluate the polynomial at x = 5
value = p(5)
print(value)  # 86

# Polynomial operations
p2 = Polynomial([0, 1, 1])
sum_polynomial = p + p2
print(sum_polynomial)  # Polynomial([1, 3, 4], domain=[-1, 1], window=[-1, 1])


86.0
1.0 + 3.0 x + 4.0 x**2


In [22]:
# Fourier Transform
from numpy.fft import fft, ifft

# Create a sample signal
signal = np.array([0, 1, 0, -1])

# Compute the Fast Fourier Transform
fft_result = fft(signal)
print(fft_result)

# Compute the Inverse Fast Fourier Transform
ifft_result = ifft(fft_result)
print(ifft_result)


[0.+0.j 0.-2.j 0.+0.j 0.+2.j]
[ 0.+0.j  1.+0.j  0.+0.j -1.+0.j]


In [23]:
# Memory Layout and Views
array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a view of the original array
view = array[:, 1:3]
print(view)
# Output:
# [[2 3]
#  [5 6]]

# Modify the view
view[0, 0] = 99
print(array)
# Output:
# [[ 1 99  3]
#  [ 4  5  6]]


[[2 3]
 [5 6]]
[[ 1 99  3]
 [ 4  5  6]]


In [24]:
# Flattening and Raveling
array2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the array
flattened_array = array2d.flatten()
print(flattened_array)

# Ravel the array (returns a flattened array view)
raveled_array = array2d.ravel()
print(raveled_array)


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [25]:
#  Creating and Using Masks
array = np.array([1, 2, 3, 4, 5, 6])

# Masking with a condition
mask = (array % 2 == 0)
print(mask)  # [False  True False  True False  True]

# Use mask to filter the array
filtered_array = array[mask]
print(filtered_array)  # [2 4 6]


[False  True False  True False  True]
[2 4 6]


In [26]:
# Masking
array = np.array([10, 20, 30, 40, 50])

# Create a mask for elements greater than 25
mask = array > 25
print(mask)  # [False False  True  True  True]

# Apply the mask to filter the array
filtered_array = array[mask]
print(filtered_array)  # [30 40 50]


[False False  True  True  True]
[30 40 50]
